import logging
from datetime import datetime, timedelta
import zermeloapi

from homeassistant.components.calendar import CalendarEntity, CalendarEvent
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.typing import ConfigType, DiscoveryInfoType

from .const import DOMAIN, CONF_SCHOOL, CONF_TOKEN

_LOGGER = logging.getLogger(__name__)

def setup_platform(
    hass: HomeAssistant,
        config: ConfigType,
            add_entities: AddEntitiesCallback,
                discovery_info: DiscoveryInfoType = None,
                ) -> None:
                    """Stel het Zermelo kalender platform in via YAML configuration."""
                        school = config.get(CONF_SCHOOL)
                            token = config.get(CONF_TOKEN)

                                if not school or not token:
                                        _LOGGER.error("Zermelo configuratie mist school of token!")
                                                return

                                                    add_entities([ZermeloCalendarEntity(school, token)], True)


                                                    class ZermeloCalendarEntity(CalendarEntity):
                                                        """Representatie van het Zermelo Rooster als Home Assistant Kalender."""

                                                            def __init__(self, school: str, token: str) -> None:
                                                                    """Initialiseer de kalender."""
                                                                            self._school = school
                                                                                    self._token = token
                                                                                            self._name = "Zermelo Schoolrooster"
                                                                                                    self._events: list[CalendarEvent] = []

                                                                                                        @property
                                                                                                            def name(self) -> str:
                                                                                                                    """Retourneer de naam van de entiteit."""
                                                                                                                            return self._name

                                                                                                                                @property
                                                                                                                                    def event(self) -> CalendarEvent | None:
                                                                                                                                            """Retourneer de huidige of eerstvolgende afspraak."""
                                                                                                                                                    if self._events:
                                                                                                                                                                return self._events[0]
                                                                                                                                                                        return None

                                                                                                                                                                            async def async_get_events(
                                                                                                                                                                                    self, hass: HomeAssistant, start_date: datetime, end_date: datetime
                                                                                                                                                                                        ) -> list[CalendarEvent]:
                                                                                                                                                                                                """Haal alle agenda-items op binnen een specifiek tijdsbestek."""
                                                                                                                                                                                                        return [
                                                                                                                                                                                                                    event
                                                                                                                                                                                                                                for event in self._events
                                                                                                                                                                                                                                            if start_date <= event.start <= end_date
                                                                                                                                                                                                                                                    ]

                                                                                                                                                                                                                                                        def update(self) -> None:
                                                                                                                                                                                                                                                                """Haal de nieuwste data op via de Zermelo API client."""
                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                    zermelo = zermeloapi.zermelo(self._school, "", "", teacher=False, version=3)
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                            start_unix = int(datetime.now().timestamp())
                                                                                                                                                                                                                                                                                                                        end_unix = int((datetime.now() + timedelta(days=7)).timestamp())

                                                                                                                                                                                                                                                                                                                                    appointments = zermelo.Appointments(self._token, start_unix, end_unix)
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                            new_events = []
                                                                                                                                                                                                                                                                                                                                                                        if appointments and isinstance(appointments, list):
                                                                                                                                                                                                                                                                                                                                                                                        for app in appointments:
                                                                                                                                                                                                                                                                                                                                                                                                            start_time = datetime.fromtimestamp(app.get("start"))
                                                                                                                                                                                                                                                                                                                                                                                                                                end_time = datetime.fromtimestamp(app.get("end"))
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Vak en lokaal netjes uitlezen uit de lijsten
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            subjects = ", ".join(app.get('subjects', ['Geen vak']))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                locations = ", ".join(app.get('locations', ['Geen lokaal']))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        event = CalendarEvent(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                summary=f"{subjects} - {locations}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        start=start_time,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end=end_time,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        description=f"Docent: {', '.join(app.get('teachers', []))}\nStatus: {app.get('status', 'Normaal')}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                new_events.append(event)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self._events = sorted(new_events, key=lambda x: x.start)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as ex:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _LOGGER.error("Fout tijdens het ophalen van Zermelo rooster: %s", ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            